# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b40bb7bdb6d64638d6dcdae49900f29f0d934b08ffb22637471e959d9674676efe96fe88de8ec24be62c723f85db16281c887332ca254c7f49671f921bd4ac

test:
  secret_key_base: 3b076e12cb983709ee962231a9dd4d1200fbbf5e5da5b2ccf221bd0dbfa77893dc2b5cb9c29c28b3091c367272d5fc03c11d4aecaf6fcd51d8e9464382785894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
